### ISSUE TITLE
Document what's the difference from other solidity plugins

### ISSUE THREAD

**Issue by ripper234** [iolitelabs/vscode-solidity-iolite#1]
Looking at the repo's main page/doc, it's hard to understand what advantage this offers over other popular plugins e.g. [JuanBlanco.solidity plugin](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity).

**Comment by vldmkr** [comment]
Technically, the iOlite plugin is the fork of [JuanBlanco](https://github.com/juanfranblanco/vscode-solidity) plugin. The main difference is the integrated wallet. It is possible to interact with Ethereum and iOlite networks, interact with the contract directly from VSCode. Details can be found in the readme from [this](https://github.com/iolitelabs/vscode-solidity-iolite#wallet-actions) point.

**Comment by ripper234** [comment]
Awesome - thanks!
